[package]
name = "fortyone-be"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.11.1", features = ["v4", "serde"] }
rand = "0.9.0-beta.1"